# Setup
name:         Project or Site name (Architect Theme)
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      "lime0326.github.io"
locale:       "en"

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
